name: cd

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4.2.0
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version-file: '.tool-versions'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Prisma generate types and etc
        run: pnpm prisma generate

      - name: Prisma migrate
        if: github.ref == 'refs/heads/main'
        run: pnpm prisma db push
        # run: pnpm prisma db push --accept-data-loss
