name: cd

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SHADOW_DATABASE_URL: postgresql://root:root@localhost:5433/attt_shadow

    services:
      shadow_db:
        image: postgres:16
        ports:
          - 5433:5432
        env:
          POSTGRES_DB: attt_shadow
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5.0.0
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version-file: '.tool-versions'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Prisma generate types and etc
        run: pnpm prisma generate

      - name: Check for missing migration files
        run: pnpm prisma migrate diff --from-migrations ./migrations --to-schema ./schema.prisma --shadow-database-url $SHADOW_DATABASE_URL --exit-code

      - name: Apply migrations
        if: github.ref == 'refs/heads/main'
        run: pnpm prisma migrate deploy
