name: cd

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5.0.0
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version-file: '.tool-versions'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Prisma generate types and etc
        run: pnpm prisma generate

      - name: Check for missing migration files
        run: pnpm prisma migrate diff --from-migrations ./migrations --to-schema-datamodel ./schema.prisma --exit-code

      - name: Apply migrations
        if: github.ref == 'refs/heads/main'
        run: pnpm prisma migrate deploy
